site_name: DragonDinghy
site_url: https://mydomain.org/mysite
repo_url: https://github.com/Drachenkaetzchen/DragonDinghy
plugins:
  - glightbox
theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to Dark Mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to Light Mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Home: index.md
  - Guide:
    - Getting Started: getting_started.md
    - Flashing: flashing.md
    - Fans: fans.md
    - Config Reference: config_reference.md
  - Troubleshooting : troubleshooting.md
  - Specifications: specifications.md
  - Known Issues: known_issues.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - md_in_html
  - attr_list
  - abbr
  - def_list
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
